[font]
size = 21

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[window]
dynamic_padding = true
decorations = "None"

[mouse]
hide_when_typing = true

[cursor]
style = { shape = "Beam" }
vi_mode_style = { shape = "Block", blinking = "Off" }

[keyboard]
bindings = [{ key = "q", mode = "Vi", action = "ToggleViMode" }]

[colors.primary]
background = "#151521"
foreground = "#959a96"

[colors]
cursor = { cursor = '#707070' }

[colors.normal]
black = "#282a36"
red = "#a35858"
green = "#5e9a5f"
yellow = "#919062"
blue = "#5d879d"
cyan = "#6c9aa3"
magenta = "#747897"
white = "#aaaaaa"

[colors.bright]
black = "#686868"
red = "#a35858"
green = "#5e9a5f"
yellow = "#919062"
blue = "#5d879d"
cyan = "#6c9aa3"
magenta = "#747897"
white = "#aaaaaa"
