[font]
size = 22
glyph_offset = { x = 0, y = 0 }
offset = { x = 0, y = 0 }

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[font.bold]
family = "FiraCode Nerd Font"
style = "SemiBold"

[window]
dynamic_padding = true
padding = { x = 0, y = 0 }
decorations = "None"

[mouse]
hide_when_typing = true

[cursor]
style = { shape = "Beam", blinking = "Off" }
vi_mode_style = { shape = "Block", blinking = "Off" }

[keyboard]
bindings = [
  { key = "Enter", mods = "Control|Shift", action = "CreateNewWindow" },
  { key = "q", mode = "Vi", action = "ToggleViMode" },
]

[colors.primary]
background = "#151521"
foreground = "#959a96"

[colors]
cursor = { cursor = '#6a6a6a' }

[colors.normal]
black = "#282a36"
red = "#a35858"
green = "#738e52"
yellow = "#919062"
blue = "#51809a"
cyan = "#6c9aa3"
magenta = "#747897"
white = "#aaaaaa"

[colors.bright]
black = "#686868"
red = "#a35858"
green = "#738e52"
yellow = "#919062"
blue = "#51809a"
cyan = "#6c9aa3"
magenta = "#747897"
white = "#aaaaaa"
