[[components]]
workspace = "2"
command = "kitty"
args = ["-e", "bash", "/home/cjh/scripts/start-clash.sh"]

[[components]]
workspace = "13"
command = "google-chrome-stable"
args = []

[[components]]
workspace = "12"
command = "kitty"
args = ["ncmpcpp"]

[[components]]
workspace = "16"
command = "code"
args = []

[[components]]
workspace = "4"
command = "linuxqq"
args = []
