"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[manager]

prepend_keymap = [
  { on = [
    "l",
  ], exec = "plugin --sync smart-enter" },
  { on = [
    "<C-s>",
  ], exec = '''shell "$SHELL" --block --confirm''' },
  { on = [
    "<C-g>",
  ], exec = "shell lazygit --block --confirm" },
]
