[manager]
layout = [1, 3, 4]
sort_by = "natural"
sort_dir_first = true
sort_sensitive = false
sort_reverse = false
linemode = "size"

[preview]
tab_size = 2
max_width = 1200
max_height = 1500

[opener]
folder = [
  { run = 'open -R "$@"', desc = "Reveal in Finder" },
  { run = '$EDITOR "$@"' },
]
archive = [{ run = 'unar "$1"', desc = "Extract here" }]
text = [{ run = '$EDITOR "$@"', block = true }]
image = [
  { run = 'mupdf "$@"', desc = "Open" },
  { run = '''exiftool "$1"; echo "Press enter to exit"; read''', block = true, desc = "Show EXIF" },
]
video = [
  { run = 'mpv "$@"' },
  { run = '''mediainfo "$1"; echo "Press enter to exit"; read''', block = true, desc = "Show media info" },
]
audio = [
  { run = 'mpv "$@"' },
  { run = '''mediainfo "$1"; echo "Press enter to exit"; read''', block = true, desc = "Show media info" },
]
fallback = [
  { run = 'open "$@"', desc = "Open" },
  { run = 'open -R "$@"', desc = "Reveal in Finder" },
]

[tasks]
micro_workers = 5
macro_workers = 10
bizarre_retry = 5

[log]
enabled = false
